services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dockerdb
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo_service
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
